# Generated by Django 4.1.4 on 2022-12-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de inscripción')),
                ('hora_inscripcion', models.TimeField(verbose_name='Hora de inscripción')),
                ('estado', models.IntegerField(choices=[[0, 'Reservado'], [1, 'Completada'], [2, 'Anulada'], [3, 'No Asiste']], verbose_name='Estado')),
                ('observacion', models.TextField(max_length=254, verbose_name='Observación')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrito', to='app.institucion')),
            ],
        ),
    ]
